extend type Query {
  # Get movie details by ID
  movie(id: String!): Movie
}

type Movie @key(fields: "id") {
  id: ID!
  title: String!
  released: Date!
  genres: [String!]!
  directedBy: [Person!]
  writtenBy: [Person!]
  cast: [Person!]!
}

type Person @key(fields: "id") {
  id: ID!
  name: String!
  birthDate: Date!
}
